- alias: "Turn off the fan two hours after this is switched on"
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: automation.turn_off_the_fan_two_hours_after_this_is_switched_on
    to: 'on'
    for:
      hours: 2
  action:
    - service: homeassistant.turn_off
      entity_id: switch.fan
    - service: notify.ios_simons_iphone
      data_template:
        message: "Your fan was switched off at {{ now() }}."
    - service: homeassistant.turn_off
      entity_id: automation.turn_off_the_fan_two_hours_after_this_is_switched_on


- alias: "ONLY run the fan for two hours"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: switch.fan
    to: 'on'
    for:
      hours: 2
  action:
    - service: homeassistant.turn_off
      entity_id: switch.fan
    - service: notify.lily_flavelles_iphone
      data_template:
        message: "Your fan was switched off at {{ now() }}."
