- alias: "Lights on when I'm working"
  initial_state: 'on'
  trigger:
    platform: time
    at: '04:30:00'
  condition:
    condition: state
    entity_id: input_boolean.work_routines
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.wakeup_lights

- alias: "Heater on when I leave work"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.simon_presence
    from: 'At Work'
  condition:
    condition: state
    entity_id: input_boolean.work_routines
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.heater

- alias: "Light on when I get home from work"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.simon_presence
    from: 'Away'
    to: 'At Home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.work_routines
        state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.simon