# This config uses:
# Custom-UI by @andrey-git
# ha-history-stats by @bokub

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret loc_lat
  longitude: !secret loc_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret loc_elv
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  customize_glob: !include customize.yaml

# Location zoning

zone:
  - name: Simon's Work
    latitude: !secret loc_boris_lat
    longitude: !secret loc_boris_lon
    

# Enables the frontend
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-mini-media-player.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-mini-media-player_es5.html

customizer:
  custom_ui: local
  columns: 
    - 500
    - 800
    - 1100 
    - 1400

# Enables configuration UI
config:

# Enables Map UI
map:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret url
  ssl_certificate: !secret sslcert
  ssl_key: !secret sslkey

recorder:
  exclude:
    domains:
      - automation
      - weblink
      - updater


# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - group
    entities:
      - sensor.chicago_time
      - sensor.london_time

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
    entities:
      - sensor.average_load_15m
      - sensor.average_load_1m
      - sensor.external_ip
      - sensor.chicago_time
      - sensor.london_time

# Track the sun
sun:

# Text to speech
tts:
  platform: google

ifttt:
  key: !secret ifttt_key

duckdns:
  domain: !secret ddns_domain
  access_token: !secret ddns_token

ios:

# Google Assistant

google_assistant:
  project_id: homeassistneu
  client_id: !secret ga_client
  access_token: !secret ga_access
  agent_user_id: simonsayslps@gmail.com
  api_key: !secret ga_api
  exposed_domains:
    - switch
    - light
  entity_config:
    switch.discord_neubott:
      name: Neubott
      aliases:
        - Neubott
        - Neutopia bot
    switch.discord_bucket:
      name: Bucket
      aliases:
        - Bucket
        - Bucket bot
        - General Chat bot
    switch.mac_display:
      name: Mac Mini
      aliases:
        - Mac Mini
        - Mac
        - Mac display

mqtt:
  broker: !secret mqttbroker
  port: 19356
  username: !secret mqttuser
  password: !secret mqttpassword

# Component/Entity Configuration

camera:
  - platform: generic
    still_image_url: http://www.bom.gov.au/radar/IDR023.gif?{{ now().strftime("%Y%m%d%H%M") }}00
    name: Rain Radar
    limit_refetch_to_url_change: true
  - platform: local_file
    file_path: /Users/lily/Webcam.jpg
    name: Bedroom

# Smart Devices

wemo:
  static:
    - 192.168.0.100
    - 192.168.0.101

light:
  - platform: lifx

# Various Location Tracking

device_tracker:
  - platform: icloud
    username: !secret icloud_user
    password: !secret icloud_pass

media_player: !include_dir_merge_list cfg/media
media_extractor: # Enable media_extractor service
binary_sensor: !include_dir_merge_list cfg/sensors_binary/
sensor: !include_dir_merge_list cfg/sensors/
switch: !include_dir_merge_list cfg/switches/

scene: !include_dir_merge_list cfg/scenes/

# Notification Platforms

notify:
  - name: discord
    platform: discord
    token: !secret discord_token
  - name: telegrambot
    platform: telegram
    chat_id: !secret tgram_simon

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram
    allowed_chat_ids:
      - !secret tgram_simon

group: !include_dir_merge_named cfg/groups/
automation: !include_dir_merge_list cfg/auto/
script: !include_dir_merge_named cfg/scripts/

# Custom Inputs

input_select: !include_dir_merge_named cfg/input/select/
input_text: !include_dir_merge_named cfg/input/text/
input_boolean: !include_dir_merge_named cfg/input/boolean/

# Various Hubs

apple_tv:
  - host: 192.168.0.62
    login_id: 00000000-6075-0234-de72-4422edd64499

# Components that don't need files

history_graph:
  tempgraph:
    name: Recent Temperatures
    entities:
    - sensor.bom_bendigo_air_temp_c
    - sensor.bom_bendigo_rain_today
    - sensor.bom_bendigo_relative_humidity
    - sensor.bom_bendigo_wind_speed_kmh
    hours_to_show: 72
    refresh: 3600
  netgraph:
    name: Network Speeds
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
    hours_to_show: 72
    refresh: 3600

device_sun_light_trigger:
  light_group: group.simons_lights
  device_group: group.tracked_devices

timer:
  laundry_line:
    duration: '08:00:00'
  laundry_dryer:
    duration: '01:30:00'
