# This config uses:
# Custom-UI by @andrey-git
# ha-history-stats by @bokub

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret loc_lat
  longitude: !secret loc_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret loc_elv
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  customize_glob: !include customize.yaml

# Location zoning

zone:
  - name: Simon's Work
    latitude: !secret loc_boris_lat
    longitude: !secret loc_boris_lon
    

# Enables the frontend
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-mini-media-player.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-mini-media-player_es5.html
  themes:
    dark_theme: # Copied from https://community.home-assistant.io/t/another-dark-theme/28595
      # Main Stuff #
      primary-color: "#1ABA92" # Primary (most of the UI)
      primary-background-color: "#303030" # Primary background colour (dialogs, e.t.c)
      secondary-background-color: "#303030" # Secondary background colour (main UI background)
      paper-card-background-color: "#424242" # Card background colour
      paper-item-icon-color: "#1ABA92" # Icon colour
      primary-text-color: "#FFFFFF" # Primary text colour
      secondary-text-color: "rgba(255, 255, 255, 0.7)" # Secondary text colour
      disabled-text-color: "rgba(255, 255, 255, 0.5)" # Disabled text colour
      divider-color: "rgba(255, 255, 255, 0.12)" # Divider colour
      paper-card-header-color: "#FFFFFF" # Card header text colour
      # Nav Menu #
      paper-listbox-background-color: "#424242" # Listbox background colour
      paper-listbox-color: "#FFFFFF" # Listbox text colour
      paper-grey-200: "#616161" # Listbox selected item background colour
      # Switches #
      paper-toggle-button-checked-ink-color: "#1ABA92"
      paper-toggle-button-checked-button-color: "#1ABA92"
      paper-toggle-button-checked-bar-color: "#1ABA92"
      # Sliders #
      paper-slider-knob-color: "#1ABA92"
      paper-slider-knob-start-color: "#1ABA92"
      paper-slider-pin-color: "#1ABA92"
      paper-slider-active-color: "#1ABA92"
      paper-slider-secondary-color: "#33F2D8"

customizer:
  custom_ui: hosted
  columns: 
    - 500
    - 800
    - 1100 
    - 1400

# Enables configuration UI
config:

# Enables Map UI
map:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret url
  ssl_certificate: !secret sslcert
  ssl_key: !secret sslkey

recorder:
  exclude:
    domains:
      - automation
      - weblink
      - updater


# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - group
      - input_text
      - input_boolean
      - timer
      - history_graph
    entities:
      - sensor.chicago_time
      - sensor.london_time
      - sensor.california_time

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
    entities:
      - sensor.average_load_15m
      - sensor.average_load_1m
      - sensor.external_ip
      - sensor.chicago_time
      - sensor.london_time
      - sensor.california_time

# Track the sun
sun:

# Text to speech
tts:
  platform: google

ifttt:
  key: !secret ifttt_key

duckdns:
  domain: !secret ddns_domain
  access_token: !secret ddns_token

ios:

# Home Control Services

google_assistant:
  project_id: homeassistneu
  client_id: !secret ga_client
  access_token: !secret ga_access
  agent_user_id: simonsayslps@gmail.com
  api_key: !secret ga_api
  exposed_domains:
    - switch
    - light
  entity_config:
    switch.discord_neubott:
      name: Neubott
      aliases:
        - Neubott
        - Neutopia bot
    switch.discord_bucket:
      name: Bucket
      aliases:
        - Bucket
        - Bucket bot
        - General Chat bot
    switch.display_debian:
      name: Mac Mini
      aliases:
        - Mac Mini
        - Mac
        - Mac display
        - server display

cloud:
  alexa:
    filter:
      exclude_domains:
        - group
        - remote
        - automation
        - sensor

homekit:
  auto_start: false
  filter:
    exclude_domains:
      - automation
      - remote
      - group
      - timer
    exclude_entities:
      - sensor.iphone_battery_level
      - sensor.batt_ipad
      - sensor.batt_iphone
      - sensor.batt_nexus
      - sensor.batt_watch
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_temperature


mqtt:
  # broker: !secret mqttbroker
  # port: 19356
  # username: !secret mqttuser
  # password: !secret mqttpassword

# Component/Entity Configuration

camera:
  - platform: generic
    still_image_url: http://www.bom.gov.au/radar/IDR023.gif?{{ now().strftime("%Y%m%d%H%M") }}00
    name: Rain Radar
    limit_refetch_to_url_change: true

wake_on_lan:

# Smart Devices

wemo:
  static:
    - 192.168.0.100
    - 192.168.0.101

light:
  - platform: lifx

# Various Location Tracking

device_tracker:
  - platform: icloud
    username: !secret icloud_user
    password: !secret icloud_pass
  - platform: gpslogger

media_player: !include_dir_merge_list cfg/media/
media_extractor: # Enable media_extractor service
binary_sensor: !include_dir_merge_list cfg/sensors_binary/
sensor: !include_dir_merge_list cfg/sensors/
switch: !include_dir_merge_list cfg/switches/

scene: !include_dir_merge_list cfg/scenes/

# Notification Platforms

notify:
  - name: discord
    platform: discord
    token: !secret discord_token

group: !include_dir_merge_named cfg/groups/
automation: !include_dir_merge_list cfg/auto/
script: !include_dir_merge_named cfg/scripts/

# Custom Inputs

input_select: !include_dir_merge_named cfg/input_select/

# Various Hubs

apple_tv:
  - host: 192.168.0.62
    login_id: 00000000-6075-0234-de72-4422edd64499

# Components that don't need files

history_graph:
  tempgraph:
    name: Recent Temperatures
    entities:
    - sensor.bom_bendigo_air_temp_c
    hours_to_show: 144
    refresh: 1800
  netgraph:
    name: Network Speeds
    entities:
      - sensor.speedtest_download
      - sensor.speedtest_upload
    hours_to_show: 144
    refresh: 3600

timer:
  laundry_line:
    duration: '08:00:00'
  laundry_dryer:
    duration: '01:30:00'

shell_command:
  shutdown_windows: sshpass -f /config/.windows ssh me@192.168.0.61 "C:\Windows\System32\shutdown.exe /s /t 60"