# This config uses:
# Custom-UI by @andrey-git
# ha-history-stats by @bokub

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret loc_lat
  longitude: !secret loc_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret loc_elv
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  customize_glob: !include customize.yaml
  packages: !include_dir_named cfg/packages
  whitelist_external_dirs:
    - /mnt/plexvideo
    - /mnt/media
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

# Location zoning

zone:
  - name: Simon's Work
    latitude: !secret loc_work_lat
    longitude: !secret loc_work_lon
    radius: 300
    

# Enables the frontend
frontend:
  javascript_version: latest
  themes:
    dark_theme: # Copied from https://community.home-assistant.io/t/another-dark-theme/28595
      # Main Stuff #
      primary-color: "#1ABA92" # Primary (most of the UI)
      primary-background-color: "#303030" # Primary background colour (dialogs, e.t.c)
      secondary-background-color: "#303030" # Secondary background colour (main UI background)
      paper-card-background-color: "#424242" # Card background colour
      paper-item-icon-color: "#1ABA92" # Icon colour
      primary-text-color: "#FFFFFF" # Primary text colour
      secondary-text-color: "rgba(255, 255, 255, 0.7)" # Secondary text colour
      disabled-text-color: "rgba(255, 255, 255, 0.5)" # Disabled text colour
      divider-color: "rgba(255, 255, 255, 0.12)" # Divider colour
      paper-card-header-color: "#FFFFFF" # Card header text colour
      # Nav Menu #
      paper-listbox-background-color: "#424242" # Listbox background colour
      paper-listbox-color: "#FFFFFF" # Listbox text colour
      paper-grey-200: "#616161" # Listbox selected item background colour
      # Switches #
      paper-toggle-button-checked-ink-color: "#1ABA92"
      paper-toggle-button-checked-button-color: "#1ABA92"
      paper-toggle-button-checked-bar-color: "#1ABA92"
      # Sliders #
      paper-slider-knob-color: "#1ABA92"
      paper-slider-knob-start-color: "#1ABA92"
      paper-slider-pin-color: "#1ABA92"
      paper-slider-active-color: "#1ABA92"
      paper-slider-secondary-color: "#33F2D8"
    splat_squidsisters:
      # Primary Config
      primary-color: "var(--callie-color)"
      accent-color: "var(--marie-color)"
      callie-color: "#df1086" # Callie primary color
      marie-color: "#24f834" # Marie primary color
      dark-color: "#272727" # Dark background light stripe
      darker-color: "#19171a" # Dark background dark stripe
      heading-font: "Splatoon1, 'Roboto', 'Noto', sans-serif"
      body-font: "Splatoon2, 'Roboto', 'Noto', sans-serif"
      # Cards
      primary-background-color: "var(--darker-color)"
      paper-card-background-color: "var(--dark-color)"
      paper-card-header-color: "var(--callie-color)"
      primary-text-color: "#FFFFFF" # Primary text colour
      secondary-text-color: "rgba(255, 255, 255, 0.7)" # Secondary text colour
      disabled-text-color: "rgba(255, 255, 255, 0.5)" # Disabled text colour
      # Icons
      state-icon-active-color: "var(--callie-color)"
      paper-item-icon-color: "#5d2cc4"
      sidebar-icon-color: "var(--marie-color)"
      # Other UI
      paper-listbox-color: "#FFFFFF" 
      paper-listbox-background-color: "var(--darker-color)"
      more-info-header-background: "var(--marie-color)"
      # Other Colors
      label-badge-green: "#29ee86"
      label-badge-yellow: "#fceb3f"
      label-badge-red: "#ff9936"
      # Font Settings
      paper-font-headline_-_font-family: "var(--heading-font)"
      paper-font-body1_-_font-family: "var(--body-font)"
      paper-font-caption_-_font-family: "var(--body-font)"
      paper-input-container-shared-input-style_-_font-family: "var(--body-font)"
    splat_offthehook:
      # Primary Config
      primary-color: "var(--pearl-color)"
      accent-color: "var(--marina-color)"
      pearl-color: "#fa48ad" # Callie primary color
      marina-color: "#03e297" # Marie primary color
      dark-color: "#272727" # Dark background light stripe
      darker-color: "#19171a" # Dark background dark stripe
      primary-background-color: "#a7a3b6"
      paper-card-background-color: "#b8b0b4"
      heading-font: "Splatoon1, 'Roboto', 'Noto', sans-serif"
      body-font: "Splatoon2, 'Roboto', 'Noto', sans-serif"
      # Cards
      paper-card-header-color: "var(--pearl-color)"
      # Icons
      state-icon-active-color: "var(--pearl-color)"
      paper-item-icon-color: "#5d2cc4"
      sidebar-icon-color: "var(--marina-color)"
      # Other UI
      more-info-header-background: "var(--marina-color)"
      # Other Colors
      label-badge-green: "#29ee86"
      label-badge-yellow: "#fceb3f"
      label-badge-red: "#ff9936"      
      # Font Settings
      paper-font-headline_-_font-family: "var(--heading-font)"
      paper-font-body1_-_font-family: "var(--body-font)"
      paper-font-caption_-_font-family: "var(--body-font)"
      paper-input-container-shared-input-style_-_font-family: "var(--body-font)"
      

# Enables configuration UI
config:

custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/rdehuyss/homeassistant-lovelace-google-calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kuuji/button-card/0.0.2/tracker.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json

# Enables Map UI
map:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret url
  ssl_certificate: !secret sslcert
  ssl_key: !secret sslkey

recorder:
  exclude:
    domains:
      - automation
      - weblink
      - updater


# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - group
      - input_text
      - input_boolean
      - timer
      - history_graph
    entities:
      - sensor.chicago_time
      - sensor.london_time
      - sensor.california_time

# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
    entities:
      - sensor.average_load_15m
      - sensor.average_load_1m
      - sensor.external_ip
      - sensor.chicago_time
      - sensor.london_time
      - sensor.california_time

# Track the sun
sun:

# Text to speech
tts:
  platform: google

ifttt:
  key: !secret ifttt_key

duckdns:
  domain: !secret ddns_domain
  access_token: !secret ddns_token

ios:

# Home Control Services

google_assistant:
  project_id: homeassistneu
  api_key: !secret ga_api
  exposed_domains:
    - switch
    - light
  entity_config:
    switch.discord_neubott:
      name: Neubott
      aliases:
        - Neubott
        - Neutopia bot
    switch.discord_bucket:
      name: Bucket
      aliases:
        - Bucket
        - Bucket bot
        - General Chat bot
    switch.display_debian:
      name: Mac Mini
      aliases:
        - Mac Mini
        - Mac
        - Mac display
        - server display

cloud:
  alexa:
    filter:
      exclude_domains:
        - group
        - remote
        - automation
        - sensor
  google_actions:
    filter:
      exclude_domains:
        - group
        - remote
        - automation
      include_entities:
        - input_boolean.work_routines
    entity_config:
      switch.docker_bucket:
        name: Bucket Bot
        aliases:
          - Bucket
          - Tedbeet Bot
          - General Chat Bot
      switch.docker_neubott:
        name: Neubott
        aliases:
          - Neutopia Bot
          - My server bot
      switch.forever_nodered:
        name: Node RED
      input_boolean.work_routines:
        name: Alarm

homekit:
  auto_start: false
  filter:
    exclude_domains:
      - automation
      - device_tracker
      - remote
      - group
      - timer
    exclude_entities:
      - sensor.iphone_battery_level
      - sensor.batt_ipad
      - sensor.batt_iphone
      - sensor.batt_nexus
      - sensor.batt_watch
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_temperature
    include_entities:
      - input_boolean.work_routines
  entity_config:
    input_boolean.work_routines:
      name: Alarm

mqtt:
  broker: !secret mqttbroker
  port: 10122
  username: !secret mqttuser
  password: !secret mqttpassword

notify:
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_api
    gcm_sender_id: !secret gcm_sender

# Component/Entity Configuration

camera:
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=049&brand=wui&num=10&delay=50&type=A0Q&frame=0&scale=0.25&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=772&centery=20&transx=372&transy=-220&showlabels=1&severe=0&rainsnow=1&lightning=1&smooth=0&rand=25405942&lat=0&lon=0&label=you
    name: Weather Radar
    limit_refetch_to_url_change: true
  - platform: push
    name: Splatoon 2 - Most Recent Battle
    field: file

weather:
  - platform: darksky
    api_key: !secret darksky

wake_on_lan:

# Smart Devices

wemo:
  static:
    - 192.168.0.100
    # - 192.168.0.101

# Various Location Tracking

device_tracker:
  - platform: icloud
    username: !secret icloud_user
    password: !secret icloud_pass
  - platform: netgear
    host: 192.168.0.1
    password: !secret router_pass
  - platform: gpslogger
  - platform: tile
    username: !secret tile_user
    password: !secret tile_pass

media_player: !include_dir_merge_list cfg/media/
media_extractor: # Enable media_extractor service
binary_sensor: !include_dir_merge_list cfg/sensors_binary/
sensor: !include_dir_merge_list cfg/sensors/
switch: !include_dir_merge_list cfg/switches/
scene: !include_dir_merge_list cfg/scenes/
group: !include_dir_merge_named cfg/groups/
automation: !include_dir_merge_list cfg/auto/
script: !include_dir_merge_named cfg/scripts/

input_select:
  simon_presence:
    options:
      - At Home
      - In Bed
      - At Work
      - Away
    name: Simon

# Various Hubs

apple_tv:
  - host: 192.168.0.62
    login_id: 00000000-6075-0234-de72-4422edd64499
