title: Home
resources:
  - url: /local/tracker-card.js?v=0.1.4
    type: js
  - url: /local/custom-lovelace/bignumber-card/bignumber-card.js?v=0.0.1
    type: js
  - url: /local/custom-lovelace/entity-attributes-card/entity-attributes-card.js?v=0.1.0
    type: js
  - url: /local/vertical-stack-in-card.js?v=0.0.6
    type: js
  - url: /local/custom-lovelace/group-card/group-card.js?v=0.0.2
    type: js
  - url: /local/list-card.js?v=0.0.6
    type: js
  - url: /local/ext-weblink.js?v=0.3.2
    type: js
  - url: /local/button-card.js
    type: module
views:
  - title: Dashboard
    id: home
    icon: mdi:home
    badges:
      - sun.sun
    cards:
      - type: custom:bignumber-card
        entity: sensor.time
      - type: entity-filter
        entities:
          - device_tracker.bethsiphone
          - entity: device_tracker.heytherecharlie
            name: Simon
          - device_tracker.izzysiphone
          - device_tracker.johnsiphone
          - device_tracker.michelesiphone
        state_filter:
          - 'home'
        card: 
          type: glance
          title: People at home
          show_state: false
      - type: weather-forecast
        entity: weather.dark_sky
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:bignumber-card
                title: Download
                entity: sensor.speedtest_download
                scale: 20px
                min: 0
                max: 20
              - type: custom:bignumber-card
                title: Upload
                entity: sensor.speedtest_upload
                scale: 20px
                min: 0
                max: 2
          - type: history-graph
            title: Network Speeds
            refresh_interval: 3600
            hours_to_show: 48
            entities:
              - sensor.speedtest_download
              - sensor.average_download_speed_mean
              - sensor.speedtest_upload
      - type: glance
        title: Around The World
        entities:
          - sensor.chicago_time
          - sensor.london_time
          - sensor.california_time
  - title: Lounge
    icon: mdi:sofa
    id: lounge
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: media-control
            entity: media_player.apple_tv
          - type: entities
            title: Other TV Devices
            show_header_toggle: false
            entities: 
              - media_player.playstation_4
  - title: Simon's Room
    id: simon
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:bignumber-card
            title: iPhone
            entity: sensor.batt_iphone
            scale: 20px
            min: 0
            max: 100
            severity:
              - value: 15
                style: 'var(--label-badge-red)'
              - value: 35
                style: 'var(--label-badge-yellow)'
              - value: 100
                style: 'var(--label-badge-green)'
          - type: custom:bignumber-card
            title: iPad
            entity: sensor.batt_ipad
            scale: 20px
            min: 0
            max: 100
            severity:
              - value: 15
                style: 'var(--label-badge-red)'
              - value: 35
                style: 'var(--label-badge-yellow)'
              - value: 100
                style: 'var(--label-badge-green)'
          - type: custom:bignumber-card
            title: Apple Watch
            entity: sensor.batt_watch
            scale: 20px
            min: 0
            max: 100
            severity:
              - value: 25
                style: 'var(--label-badge-red)'
              - value: 50
                style: 'var(--label-badge-yellow)'
              - value: 100
                style: 'var(--label-badge-green)'
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - input_select.simon_presence
              - sensor.commute_time
              - sensor.payslip_date
          - type: horizontal-stack
            cards:
              - type: custom:button-card
                entity: light.simon
                action: toggle
                icon: mdi:lightbulb
                color: var(--primary-color)
              - type: custom:button-card
                entity: switch.heater
                action: toggle
                icon: mdi:radiator
                color: var(--primary-color)
              - type: custom:button-card
                entity: switch.fan
                action: toggle
                icon: mdi:fan
                color: var(--primary-color)
              - type: custom:button-card
                entity: switch.gaming_pc
                action: toggle
                icon: mdi:monitor
                color: var(--accent-color)
      - type: vertical-stack
        cards:
          - type: glance
            show_name: false
            show_state: false
            entities:
              - entity: light.simon
                tap_action: more-info
              - entity: scene.sleep__night_light
                name: Red
                tap_action: call-service
                service: scene.turn_on
              - entity: scene.evening_warm_lighting
                name: Warm
                tap_action: call-service
                service: scene.turn_on
              - entity: scene.daylight_cool_lighting
                name: Bright
                tap_action: call-service
                service: scene.turn_on
              - entity: script.wakeup_lights
                name: Fade
                tap_action: call-service
                service: script.wakeup_lights
          - type: glance
            show_name: false
            entities:
              - entity: switch.fan
                secondary_info: last-changed
                tap_action: toggle
              - entity: automation.turn_off_the_fan_two_hours_after_this_is_switched_on
                name: Timer
                tap_action: toggle
              - entity: automation.only_run_the_fan_for_two_hours
                name: Power Save
                tap_action: toggle
          - type: glance
            show_name: false
            entities:
              - entity: switch.heater
                secondary_info: last-changed
                tap_action: toggle
              - entity: automation.turn_off_the_heater_two_hours_after_this_is_switched_on
                name: Timer
                tap_action: toggle
              - entity: automation.only_run_the_heater_for_two_hours
                name: Power Save
                tap_action: toggle
          - type: entities
            title: Alarm
            entities:
              - entity: input_boolean.work_routines
                name: Set Alarm
              - input_select.simon_alarmsound
              - entity: input_datetime.simon_alarmtime
                name: "Set Alarm For:"
      - type: media-control
        entity: media_player.chromecast_simon
      - type: entities
        title: Music Devices
        show_header_toggle: false
        entities:
          - type: media-control
            entity: media_player.google_home_simon
          - type: media-control
            entity: media_player.spotify
          - media_player.mopidy_icecast
      - type: history-graph
        refresh_interval: 300
        entities:
          - light.simon
          - switch.heater
          - switch.fan
          - switch.gaming_pc
          - entity: media_player.google_home_simon
            name: Google Home
          - entity: media_player.chromecast_simon
            name: Chromecast

  - title: Games
    id: games
    icon: mdi:gamepad-variant
    background: center / cover repeat url("/local/img/spl2-bg-dark.png")
    cards:
      - type: vertical-stack
        cards:
          - type: picture
            image: https://pbs.twimg.com/media/Dlan8b_VAAAJP-S.jpg:orig
          - type: entities
            title: Splatoon 2
            entities:
              - type: custom:ext-weblink
                url: https://stat.ink/@Neurario
                entity: sensor.splatoon_2__battles_fought
                name: Battles Fought (Recorded)
                secondary_info: last-changed
                icon: mdi:newspaper
              - type: custom:bignumber-card
                title: Win Percentage (Last 50 Battles)
                entity: sensor.splatoon_2__win_percentage_last_50_battles
                scale: 20px
                min: 0
                max: 100
                severity:
                  - value: 100
                    style: 'var(--accent-color)'
              - type: custom:bignumber-card
                title: Win Percentage (Ranked Only)
                entity: sensor.splatoon_2__ranked_battle_win_percentage
                scale: 20px
                min: 0
                max: 100
                severity:
                  - value: 100
                    style: 'var(--accent-color)'
              - type: custom:bignumber-card
                title: Win Percentage (Last 24 Hours)
                entity: sensor.splatoon_2__win_percentage_last_24h
                scale: 20px
                min: 0
                max: 100
                severity:
                  - value: 100
                    style: 'var(--accent-color)'
              - entity: sensor.splatoon_2__splat_average
                name: Splat Average per Game (Last 50 Battles)
              - entity: sensor.splatoon_2__splatted_average 
                name: Splatted Average per Game (Last 50 Battles)
              - type: divider
              - entity: sensor.splatoon_2__turf_ink_average
                name: Turf War - Average Turf Inked
              - entity: sensor.splatoon_2__total_turf_inked
                name: Turf War - Total Turf Inked
              - type: picture-entity
                entity: camera.splatoon_2__most_recent_battle
                show_state: false
              - type: custom:list-card
                entity: sensor.splatoon_2_log
                row_limit: 10
                title: Recent Battles
                columns:
                  - title: Date
                    field: published
                  - title: Mode
                    field: title
                    regex: "(Turf War|Tower Control|Rainmaker|Clam Blitz|Splat Zones)"
                  - title: Stage
                    field: title
                    regex: "/ (.+?) /"
                  - title: Result
                    field: title
                    add_link: link
                    regex: "(Lost|Won)"

  - title: Applications / Servers
    id: servers
    icon: mdi:settings
    background: center / cover repeat url("/local/img/spl2-bg-dark.png")
    cards:
      - type: entities
        title: Mac Mini Servers
        entities:
          - entity: switch.forever_nodered
            name: Node-RED
          - switch.docker_neubott
          - switch.docker_tgbridge
          - switch.docker_icecast
      - type: custom:tracker-card
        title: Updates
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
      - type: custom:vertical-stack-in-card
        cards:
          - type: entities
            title: Server Info (Mac Mini)
            entities:
              - sensor.last_boot
          - type: custom:bignumber-card
            title: Disk Usage (/)
            entity: sensor.disk_use_percent_
            scale: 30px
            min: 0
            max: 100
            severity:
              - value: 75
                style: 'var(--label-badge-green)'
              - value: 85
                style: 'var(--label-badge-yellow)'
              - value: 95
                style: 'var(--label-badge-red)'
          - type: custom:bignumber-card
            title: Disk Usage (/mnt/media)
            entity: sensor.disk_use_percent_mntmedia
            scale: 30px
            min: 0
            max: 100
            severity:
              - value: 75
                style: 'var(--label-badge-green)'
              - value: 85
                style: 'var(--label-badge-yellow)'
              - value: 95
                style: 'var(--label-badge-red)'
          - type: custom:bignumber-card
            title: Disk Usage (/mnt/plexvideo)
            entity: sensor.disk_use_percent_mntplexvideo
            scale: 30px
            min: 0
            max: 100
            severity:
              - value: 75
                style: 'var(--label-badge-green)'
              - value: 85
                style: 'var(--label-badge-yellow)'
              - value: 95
                style: 'var(--label-badge-red)'
          - type: history-graph
            refresh_interval: 3600
            entities:
              - sensor.load_1m
              - sensor.load_5m
              - sensor.load_15m
      - type: entities
        entities:
          - type: call-service
            name: HASS Server Control
            icon: mdi:server
            action_name: Reboot
            service: homeassistant.restart
            service_data:
              do_it: 'yes'
  - title: Bucket Server
    id: bucket
    icon: mdi:bitbucket
    cards:
      - type: custom:bignumber-card
        entity: sensor.bucket_quotes
        scale: 50px
      - type: entities
        title: Words of Wisdom
        entities:
          - entity: sensor.bucket_facts
            secondary_info: last-changed
          - entity: sensor.bucket_protips
            secondary_info: last-changed
      - type: entities
        title: Generic Triggers
        entities:
          - entity: sensor.general_chat_jams
            secondary_info: last-changed
          - entity: sensor.raocowisms
            secondary_info: last-changed
            name: Raocow 'Things'
          - entity: sensor.what_did_general_chat_miss
            secondary_info: last-changed
          - entity: sensor.splatoon_things
            secondary_info: last-changed
            name: "Gimme Squids"
          - entity: sensor.battle_royale_memes
            secondary_info: last-changed
            name: "100 Xs Parachute Into A Y"
      - type: glance
        title: Factoids about People
        column_width: calc(100% / 5)
        entities:
          - entity: sensor.ash_factoids
            name: Ash
          - entity: sensor.brian_factoids
            name: Brian
          - entity: sensor.bucket_factoids
            name: Bucket
          - entity: sensor.casey_factoids
            name: Casey
          - entity: sensor.harley_factoids
            name: Harley
          - entity: sensor.hinchy_factoids
            name: Hinchy
          - entity: sensor.neu_factoids
            name: Lily
          - entity: sensor.phil_factoids
            name: Phil
          - entity: sensor.quetz_factoids
            name: Quetz
          - entity: sensor.sam_factoids
            name: Sam
          - entity: sensor.spicy_factoids
            name: Spicy
          - entity: sensor.spriteclad_factoids
            name: Spriteclad
          - entity: sensor.ted_facts
            name: Ted
          - entity: sensor.teriki_factoids
            name: Teriki
          - entity: sensor.tobi_factoids
            name: Tobi
      - type: glance
        title: Image Triggers
        column_width: calc(100% / 3)
        entities:
          - sensor.buns
          - sensor.buns_and_deers
          - sensor.deers