- platform: command_line
  switches:
    display_debian:
      friendly_name: Server Display
      command_on: "/usr/bin/curl -X GET http://192.168.0.60:53535/on"
      command_off: "/usr/bin/curl -X GET http://192.168.0.60:53535/off"
      command_state: "xset q | grep 'Monitor is On'"