- platform: universal
  name: Simon's Room
  children:
    - media_player.simons_tv
    - media_player.chromecast_simon
  commands:
    turn_on:
        service: media_player.turn_on
        data:
          entity_id: media_player.simons_tv
    turn_off:
        service: media_player.turn_off
        data:
          entity_id: media_player.simons_tv
- platform: plex