- platform: imap_email_content
  server: imap.gmail.com
  port: 993
  username: !secret gmail
  password: !secret gmailpass
  senders:
    - !secret gmailpayslips
  name: Recent Payslip Data
- platform: template
  sensors:
    payslip_date:
      friendly_name: Latest Payslip
      entity_id: sensor.recent_payslip_data
      value_template: >-
        {% if state_attr('sensor.recent_payslip_data', 'date') != "None" %}
          {{ strptime(state_attr('sensor.recent_payslip_data', 'date'), '%A %I:%M%p') }}"
        {% else %}
          No History
        {% endif %}